[package]
name = "text-editor"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
crossterm = "0.29.0"
ratatui = "0.30.0"
ropey = "1.6.1"
serde = "1.0.228"
serde_json = "1.0.149"
tree-sitter = "0.26.5"
tree-sitter-rust = "0.24.0"
tui-markdown = "0.3"